spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_demo
    username: root
    password: Xjj955&Wgl945
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    cn.noahcode: info
  file:
    path: log/blog-pro.log

